services:
  #################################################
  # OCTANE:FRANKENPHP
  #################################################
  app:
    image: ghcr.io/y-l-g/chat-laravel-inertia-primevue:main
    volumes:
      - laravel_chat_app_app_data:/data
      - laravel_chat_app_app_config:/config
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      start_period: 20s
    command: sh -c 'php artisan octane:frankenphp --host=0.0.0.0'
    environment:
      - APP_NAME=laravel_chat_app
    secrets:
      - laravel_chat_app_DB_PASSWORD
      - laravel_chat_app_REDIS_PASSWORD
      - laravel_chat_app_APP_URL
      - laravel_chat_app_APP_KEY
      - laravel_chat_app_REVERB_APP_SECRET
      - laravel_chat_app_REVERB_APP_KEY
      - laravel_chat_app_REVERB_APP_ID
      - laravel_chat_app_APP_DOMAIN
    entrypoint: start-container
    networks:
      - laravel_chat_app
      - caddy_network
  ##################################################
  # HORIZON
  ##################################################
  horizon:
    image: ghcr.io/y-l-g/chat-laravel-inertia-primevue:main
    volumes:
      - laravel_chat_app_horizon_data:/data
      - laravel_chat_app_horizon_config:/config
    command: ["php", "artisan", "horizon"]
    healthcheck:
      test: ["CMD", "php", "artisan", "horizon:status"]
    secrets:
      - laravel_chat_app_DB_PASSWORD
      - laravel_chat_app_REDIS_PASSWORD
      - laravel_chat_app_APP_URL
      - laravel_chat_app_APP_KEY
      - laravel_chat_app_REVERB_APP_SECRET
      - laravel_chat_app_REVERB_APP_KEY
      - laravel_chat_app_REVERB_APP_ID
      - laravel_chat_app_APP_DOMAIN
    entrypoint: start-container
    environment:
      - APP_NAME=laravel_chat_app
    networks:
      - laravel_chat_app
    ##################################################
  # REVERB
  ##################################################
  reverb:
    image: ghcr.io/y-l-g/chat-laravel-inertia-primevue:main
    restart: always
    volumes:
      - laravel_chat_app_reverb_data:/data
      - laravel_chat_app_reverb_config:/config
    command: ["php", "artisan", "reverb:start", "--debug"]
    secrets:
      - laravel_chat_app_DB_PASSWORD
      - laravel_chat_app_REDIS_PASSWORD
      - laravel_chat_app_APP_URL
      - laravel_chat_app_APP_KEY
      - laravel_chat_app_REVERB_APP_SECRET
      - laravel_chat_app_REVERB_APP_KEY
      - laravel_chat_app_REVERB_APP_ID
      - laravel_chat_app_APP_DOMAIN
    entrypoint: start-container
    environment:
      - APP_NAME=laravel_chat_app
    healthcheck:
      test: ["CMD", "pgrep", "-f", "reverb:start"]
      start_period: 10s
    networks:
      - laravel_chat_app
      - caddy_network
  ##################################################
  # VOLUMES
  ##################################################
volumes:
  laravel_chat_app_app_data:
  laravel_chat_app_app_config:
  ##################################################
  laravel_chat_app_horizon_data:
  laravel_chat_app_horizon_config:
  ##################################################
  laravel_chat_app_reverb_data:
  laravel_chat_app_reverb_config:
secrets:
  laravel_chat_app_DB_PASSWORD:
    external: true
  laravel_chat_app_REDIS_PASSWORD:
    external: true
  laravel_chat_app_APP_URL:
    external: true
  laravel_chat_app_APP_KEY:
    external: true
  laravel_chat_app_REVERB_APP_SECRET:
    external: true
  laravel_chat_app_REVERB_APP_KEY:
    external: true
  laravel_chat_app_REVERB_APP_ID:
    external: true
  laravel_chat_app_APP_DOMAIN:
    external: true
networks:
  laravel_chat_app:
    external: true
